name: Run Tests
run-name: API and UI tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyton-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Variable creation
      run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest UI_project/tests --headless --browser=chrome
        pytest API_project/tests -m api
