name: Run UI all tests Chrome generates report
run-name: UI all tests Chrome browser generates html report

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pyton-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Variable creation
      run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create reports directory
      run: |
        mkdir -p UI_project/reports

    - name: Run tests with pytest and generate html report
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -m web --headless --browser=chrome --html=UI_project/reports/web-report.html --self-contained-html --log-cli-level=INFO

    - name: Upload test report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-html-report
        path: UI_project/reports/web-report.html